name: Check build/run/tests

on:
  push:
    branches: [main]
  pull_request:
      # as by default
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Building library
      run: |
        mkdir build && cd build && cmake .. && make
      
  execution:
    name: Execution
    needs: [build]
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Preparing binary
      run: |
        mkdir build && cd build && cmake .. && make
    - name: Executing cputemp-monitor program
      run: |
        ./build/monitoring test

  test:
    name: Tests
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Building tests
      run: |
        cd tests
        mkdir build && cd build && cmake .. && make
    - name: Running tests
      run: |
        ctest --output-on-failure --test-dir tests/build/

